services:
  nats:
    image: nats:latest
    container_name: local-nats
    ports:
      - "4222:4222"   # NATS client port
      - "8222:8222"   # NATS HTTP monitoring port
    command: ["-js", "-m", "8222"] # Bật tính năng JetStream (-js)

  minio:
    image: cgr.dev/chainguard/minio:latest
    container_name: local-minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO Web Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  minio-init:
    image: cgr.dev/chainguard/minio-client:latest-dev
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 2;
      /usr/bin/mc alias set local http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb local/uploads local/results --ignore-existing;
      /usr/bin/mc anonymous set download local/results;
      echo 'MinIO buckets created successfully!';
      exit 0;
      "
